# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno precache and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v3

  #     - name: Setup Deno
  #       # uses: denoland/setup-deno@v1
  #       uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
  #       with:
  #         deno-version: v1.x

  #     # Uncomment this step to verify the use of 'deno fmt' on each commit.
  #     # - name: Verify formatting
  #     #   run: deno fmt --check

  #     # - name: Run linter
  #     #   run: deno lint

  #     - name: Run tests
  #       run: deno test -A
        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Build site
        run: deno run -A CI/precache.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: iiisun.art
          entrypoint: server.ts
